# Leitura dos dados

## Resumo

Esta análise tem como propósito realizar uma exploração nos dados adquiridos pelo site: http://tabnet.datasus.gov.br/ <br>
Realizar o levantamento de hipóteses e comparação com outros dados adquiridos <br>
O foco da análise será comparar o nível de analfabetismo e a quantia de vacinas aplicadas

### Leitura dados de imunos aplicados

In [42]:
import pandas as pd

In [43]:
imunos = pd.read_csv('Dados/imunos.csv', encoding="ISO-8859-1", skiprows=3, sep=";", 
                    skipfooter=19, thousands=".", decimal=",")
imunos.head()

C:\Users\Kaiqu\anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.

,Unidade da Federação,072 BCG,099 Hepatite B em crianças até 30 dias,061 Rotavírus Humano,053 Meningococo C,073 Hepatite B,080 Penta,012 Pneumocócica,074 Poliomielite,100 Poliomielite 4 anos,...,097 Tetra Viral(SRC+VZ),075 DTP,102 DTP REF (4 e 6 anos),103 Dupla Adulto (dt),095 Tríplice Bacteriana(DTP)(1º ref),018 Sarampo,009 Haemophilus influenzae b,094 Dupla adulto e tríplice acelular gestante,003 dTpa gestante,Total
0,11 Rondônia,800058,147439,325125,241025,694872,190233,239618,735112,4,...,140788,690768,9576,176383,151634,288655,73011,102081,75538,7125165
1,12 Acre,435530,70747,154135,115200,309240,86383,107866,365231,14,...,57472,290407,8007,67564,71422,98882,14394,33533,23914,3255004
2,13 Amazonas,2103147,407834,723347,578236,1421148,457595,551646,1631892,196,...,342081,1436612,32075,455475,368702,529118,125201,258975,219924,16484500
3,14 Roraima,278512,60492,107360,81724,200713,66426,82928,223108,51,...,54101,204177,5248,63330,58981,73860,19972,33663,31173,2325302
4,15 Pará,4256283,590903,1309459,916541,2740502,680391,852483,3401216,27,...,442269,3021306,50829,549869,567459,1258013,314660,293425,200201,29876882

### Leitura dados de pontuação de cobertura

In [44]:
cobertura = pd.read_csv('Dados/cobertura.csv', encoding="ISO-8859-1", skiprows=3, sep=";", 
                    skipfooter=19, thousands=".", decimal=",")
cobertura.head()

C:\Users\Kaiqu\anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.

,Unidade da Federação,072 BCG,099 Hepatite B em crianças até 30 dias,061 Rotavírus Humano,053 Meningococo C,073 Hepatite B,080 Penta,012 Pneumocócica,074 Poliomielite,100 Poliomielite 4 anos,...,098 Tríplice Viral D2,097 Tetra Viral(SRC+VZ),075 DTP,102 DTP REF (4 e 6 anos),095 Tríplice Bacteriana(DTP)(1º ref),018 Sarampo,009 Haemophilus influenzae b,094 Dupla adulto e tríplice acelular gestante,003 dTpa gestante,Total
0,11 Rondônia,105.11,77.44,61.92,60.80,91.29,87.89,89.21,96.58,0.03,...,83.98,73.95,90.75,3.84,79.65,86.23,25.12,53.88,39.87,83.29
1,12 Acre,105.54,60.09,49.50,50.59,74.94,64.19,64.09,88.50,1.87,...,54.17,48.82,70.37,4.94,60.67,69.04,11.12,28.64,20.42,67.15
2,13 Amazonas,107.99,74.39,49.73,55.81,72.97,73.35,71.17,83.79,0.18,...,69.89,62.40,73.76,4.17,67.25,72.68,19.29,47.39,40.24,72.01
3,14 Roraima,113.28,79.26,56.47,61.78,81.64,77.28,78.81,90.74,0.40,...,75.17,70.88,83.04,5.31,77.28,89.77,26.70,44.48,41.19,78.16
4,15 Pará,110.41,60.20,46.96,45.99,71.09,60.53,60.49,88.23,0.03,...,51.81,45.06,78.37,3.29,57.81,80.50,22.59,29.93,20.42,68.07

### Leiura dados analfabetismo

In [45]:
analfabetismo = pd.read_csv('Dados/analfabetismo.csv', encoding="ISO-8859-1", skiprows=3, sep=";", 
                    skipfooter=2, thousands=".", decimal=",")
analfabetismo.head()

C:\Users\Kaiqu\anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.

  Unidade da Federação  1991  2000  2010  Total
0          11 Rondônia  19.6  12.3   8.8   12.7
1              12 Acre  34.3  23.6  16.6   22.7
2          13 Amazonas  23.9  15.0   9.9   14.7
3           14 Roraima  20.0  12.2  10.3   12.7
4              15 Pará  23.4  15.9  11.6   15.8

## Tratamento Inicial: Remoção de números de UF

### dataset: Imunos

In [46]:
imunos.set_index('Unidade da Federação', inplace = True)
imunos.index = imunos.index.str[3:]
imunos.head()

,072 BCG,099 Hepatite B em crianças até 30 dias,061 Rotavírus Humano,053 Meningococo C,073 Hepatite B,080 Penta,012 Pneumocócica,074 Poliomielite,100 Poliomielite 4 anos,006 Febre Amarela,...,097 Tetra Viral(SRC+VZ),075 DTP,102 DTP REF (4 e 6 anos),103 Dupla Adulto (dt),095 Tríplice Bacteriana(DTP)(1º ref),018 Sarampo,009 Haemophilus influenzae b,094 Dupla adulto e tríplice acelular gestante,003 dTpa gestante,Total
Unidade da Federação,,,,,,,,,,,,,,,,,,,,,
Rondônia,800058,147439,325125,241025,694872,190233,239618,735112,4,700726,...,140788,690768,9576,176383,151634,288655,73011,102081,75538,7125165
Acre,435530,70747,154135,115200,309240,86383,107866,365231,14,317075,...,57472,290407,8007,67564,71422,98882,14394,33533,23914,3255004
Amazonas,2103147,407834,723347,578236,1421148,457595,551646,1631892,196,1563922,...,342081,1436612,32075,455475,368702,529118,125201,258975,219924,16484500
Roraima,278512,60492,107360,81724,200713,66426,82928,223108,51,206204,...,54101,204177,5248,63330,58981,73860,19972,33663,31173,2325302
Pará,4256283,590903,1309459,916541,2740502,680391,852483,3401216,27,2893140,...,442269,3021306,50829,549869,567459,1258013,314660,293425,200201,29876882

### dataset: Cobertura

In [47]:
cobertura.set_index('Unidade da Federação', inplace = True)
cobertura.index = cobertura.index.str[3:]
cobertura.head()

,072 BCG,099 Hepatite B em crianças até 30 dias,061 Rotavírus Humano,053 Meningococo C,073 Hepatite B,080 Penta,012 Pneumocócica,074 Poliomielite,100 Poliomielite 4 anos,006 Febre Amarela,...,098 Tríplice Viral D2,097 Tetra Viral(SRC+VZ),075 DTP,102 DTP REF (4 e 6 anos),095 Tríplice Bacteriana(DTP)(1º ref),018 Sarampo,009 Haemophilus influenzae b,094 Dupla adulto e tríplice acelular gestante,003 dTpa gestante,Total
Unidade da Federação,,,,,,,,,,,,,,,,,,,,,
Rondônia,105.11,77.44,61.92,60.80,91.29,87.89,89.21,96.58,0.03,92.06,...,83.98,73.95,90.75,3.84,79.65,86.23,25.12,53.88,39.87,83.29
Acre,105.54,60.09,49.50,50.59,74.94,64.19,64.09,88.50,1.87,76.83,...,54.17,48.82,70.37,4.94,60.67,69.04,11.12,28.64,20.42,67.15
Amazonas,107.99,74.39,49.73,55.81,72.97,73.35,71.17,83.79,0.18,80.30,...,69.89,62.40,73.76,4.17,67.25,72.68,19.29,47.39,40.24,72.01
Roraima,113.28,79.26,56.47,61.78,81.64,77.28,78.81,90.74,0.40,83.87,...,75.17,70.88,83.04,5.31,77.28,89.77,26.70,44.48,41.19,78.16
Pará,110.41,60.20,46.96,45.99,71.09,60.53,60.49,88.23,0.03,75.05,...,51.81,45.06,78.37,3.29,57.81,80.50,22.59,29.93,20.42,68.07

### dataset: analfabetismo

In [48]:
analfabetismo.set_index('Unidade da Federação', inplace = True)
analfabetismo.index = analfabetismo.index.str[3:]
analfabetismo.head()

                      1991  2000  2010  Total
Unidade da Federação
Rondônia              19.6  12.3   8.8   12.7
Acre                  34.3  23.6  16.6   22.7
Amazonas              23.9  15.0   9.9   14.7
Roraima               20.0  12.2  10.3   12.7
Pará                  23.4  15.9  11.6   15.8

### Seleção dos estados: São Paulo e Piauí

In [78]:
renome = {'Total':'total imunos'}
imunos.rename(columns = renome, inplace = True)
imunos_loc = imunos.loc[['São Paulo', 'Piauí']]['total imunos']

In [79]:
renome = {'Total':'total analfabetismo'}
analfabetismo.rename(columns = renome, inplace = True)
analfabetismo_loc = analfabetismo.loc[['São Paulo', 'Piauí']]['total analfabetismo']

In [80]:
renome = {'Total':'total cobertura'}
cobertura.rename(columns = renome, inplace = True)
cobertura_loc = cobertura.loc[['São Paulo', 'Piauí']]['total cobertura']

In [83]:
selecao = pd.DataFrame([imunos_loc, analfabetismo_loc, cobertura_loc])

In [84]:
selecao

Unidade da Federação     São Paulo        Piauí
total imunos          1.342779e+08  11098552.00
total analfabetismo   6.300000e+00        29.40
total cobertura       7.461000e+01        70.29